### ISSUE TITLE
Serde Support?

### ISSUE THREAD

**Issue by dwillie** [lifthrasiir/rust-chrono#79]
It seems like chrono has serde support but I'm getting

    error: the trait bound `chrono::DateTime<chrono::UTC>: event::serde::Deserialize` is not satisfied`

When trying to use it. I'm relatively new to Rust, am I missing something?

Thanks in advance.

edit: I'm on stable

**Comment by lifthrasiir** [comment]
It is an optional dependency, so you need to put serde to Chrono's `features`:

```toml
[dependencies]
chrono = { version = "0.2", features = ["serde"] }
```
